/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.net.URL;
import java.time.Duration;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.devtools.v120.browser.Browser;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Wait;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.github.bonigarcia.wdm.WebDriverManager;

public class QcartSanity {
    String last_userName;

    public static WebDriver browsersetup(String Browser) {
        WebDriver driver;
        switch (Browser.toLowerCase()) {
            case "chrome":
                WebDriverManager.chromedriver().setup();
                driver = new ChromeDriver();
                break;
            case "edge":
                WebDriverManager.edgedriver().setup();
                driver = new EdgeDriver();
                break;
            case "firefox":
                WebDriverManager.firefoxdriver().setup();
                driver = new FirefoxDriver();
                break;
            default:
                throw new IllegalArgumentException("Invalid Browser Name");
        }
        return driver;
    }

    public static void logstatus(String Type, String Message, String Status) {
        System.out.printf("%s | %s | %s | %s", java.time.LocalDateTime.now(), Type, Message, Status);
    }

    public static boolean TestCase_001(WebDriver driver) throws InterruptedException {
        boolean Status;
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
        logstatus("TestCase_001", "Successfully Started", "Pass");
        Home home = new Home(driver);
        home.navigatetoHomepage();
        WebDriverWait Wait = new WebDriverWait(driver, Duration.ofSeconds(50));
        Wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//P[text()=\"India’s \"]")));
        Status = home.ClickonRegister();
        if (!Status) {
            logstatus("ClickonRegister", "Failed to click on Register", "Fail");
            logstatus("Testcase_001", "Execution Failed", Status ? "Pass" : "Fail");
        }
        Register register = new Register(driver);
        register.navigatetoRegister();
        Status = register.Registeruser("Test_001", "Password@123", true);
        if (!Status) {
            logstatus("Registeruser", "Failed to Register user", "Fail");
            logstatus("Testcase_001", "Execution Failed", Status ? "Pass" : "Fail");
        }
        String last_userName = register.last_username;

        Status = register.Registeruser(last_userName, "Password@123", false);
        WebElement Alert_poup = driver.findElement(By.xpath("//div[@role='alert']"));
        try {
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[@role='alert']")));
        } catch (Exception e) {
            return false;
        }
        if (driver.getCurrentUrl().contains("/Login")) {
            logstatus("Registeruser", "Duplicate user registration allowed", "Fail");
            logstatus("Testcase_001", "Execution Failed", Status ? "Pass" : "Fail");
            return false;
        }
        String Alert_message = Alert_poup.getText();
        if (!Alert_message.contains("Username already exists")) {
            logstatus("Registeruser", "Incorrect alert message for duplicate user registration", "Fail");
            logstatus("Testcase_001", "Execution Failed", Status ? "Pass" : "Fail");
            return false;
        }
        return Status;
    }

    public static void main(String[] args) {
        int TotalTestCases = 0;
        int PassedTestCases = 0;
        boolean Status;
        WebDriver driver = browsersetup("chrome");
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
        driver.manage().window().maximize();
        try {
            TotalTestCases += 1;
            Status = TestCase_001(driver);
            if (Status) {
                PassedTestCases += 1;
            }
            System.out.println("");

        } catch (Exception e) {
            System.out.println("Exception occurred during test execution: " + e.getMessage());
        } finally {
            driver.quit();
            System.out.printf("%s Out of %s Test cases Passed", Integer.toString(PassedTestCases),
                    Integer.toString(TotalTestCases), Integer.toString((PassedTestCases * 100) / TotalTestCases));
        }
    }
}
