/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.net.URL;
import java.time.Duration;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.devtools.v120.browser.Browser;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import io.github.bonigarcia.wdm.WebDriverManager;

public class QcartSanity {

    public WebDriver browsersetup(String Browser) {
        WebDriver driver;
        switch (Browser.toLowerCase()) {
            case "chrome":
                WebDriverManager.chromedriver().setup();
                driver = new ChromeDriver();
                break;
            case "edge":
                WebDriverManager.edgedriver().setup();
                driver = new EdgeDriver();
                break;
            case "firefox":
                WebDriverManager.firefoxdriver().setup();
                driver = new FirefoxDriver();
                break;
            default:
                throw new IllegalArgumentException("Invalid Browser Name");
        }
        return driver;
    }

    public static void main(String[] args) throws InterruptedException {
        QcartSanity qs = new QcartSanity();
        WebDriver driver = qs.browsersetup("chrome");
        Home home = new Home(driver);
        home.navigatetoHomepage();
        driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));
        home.ClickonRegister();
    }
}
